name: Build & Scan Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build -t ${{ github.repository }}:latest .
    - name: Install Trivy
      run: |
        sudo apt update && sudo apt install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.47.0/trivy_0.47.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.47.0_Linux-64bit.deb
    - name: Scan Image
      run: trivy image --exit-code 1 --severity HIGH,CRITICAL ${{ github.repository }}:latest
